name: Patch Package Version
description: auto patch package.json version

author: cmtlyt
branding:
  color: blue
  icon: package

inputs:
  token:
    description: The GitHub token to use for repository operations
    required: true
  
  version-prefix:
    description: Version tag prefix (e.g., 'v', 'version-', 'rel-')
    required: false
    default: 'v'
  
  git-user-name:
    description: Git user name for commits
    required: false
    default: 'GitHub Action'
  
  git-user-email:
    description: Git user email for commits
    required: false
    default: 'action@github.com'
  
  supported-branches:
    description: Comma-separated list of supported branches
    required: false
    default: 'main,beta,alpha'
  
  enable-changelog:
    description: Enable automatic CHANGELOG generation
    required: false
    default: 'true'
  
  comment-title:
    description: Title for PR comments (e.g., '📦 版本管理', 'Version Management')
    required: false
    default: '📦 版本管理'
  
  # NPM Publishing Configuration
  enable-npm-publish:
    description: Enable automatic npm publishing
    required: false
    default: 'false'
  
  npm-token:
    description: NPM authentication token for publishing
    required: false
  
  npm-registry:
    description: NPM registry URL
    required: false
    default: 'https://registry.npmjs.org/'
  
  npm-tag:
    description: NPM publish tag (will auto-determine based on branch if set to 'latest')
    required: false
    default: 'latest'
  
  npm-access:
    description: NPM package access level (public/restricted)
    required: false
    default: 'public'
  
  npm-publish-strict:
    description: Strict mode - fail workflow if npm publish fails
    required: false
    default: 'false'

outputs:
  next-version:
    description: The next version that was calculated
  
  preview-version:
    description: Preview version for PR comments
  
  is-preview:
    description: Whether this was a preview run (true/false)
  
  # NPM Publishing Outputs
  published-version:
    description: The version that was published to npm
  
  published-tag:
    description: The npm tag used for publishing
  
  npm-registry:
    description: The npm registry that was used
  
  npm-publish-failed:
    description: Whether npm publish failed (true/false)
  
  npm-publish-error:
    description: Error message if npm publish failed

runs:
  using: node20
  main: ./dist/index.cjs
